### ISSUE TITLE
Problems for "S2F.py predict"

### ISSUE THREAD

**Issue by goes0n** [paccanarolab/S2F#12]
I try to test the predict function of S2F as follows:  "predict python S2F.py predict --config-file s2f.conf --alias myTarget --fasta target.fasta --obo ../go.obo"
The prepare data have been downloaded and prepared. But when I run the predicted command (for only one species or one protein), the following errors always show. Whats the reason and how to solve it?
![image](https://github.com/paccanarolab/S2F/assets/39076695/da51fe75-04be-40ec-9e72-17548cc6c06d)

**Comment by torresmateo** [comment]
Thanks for your question and interest in S2F. I have some comments below that I hope can help in your case.

First, predicting for a single protein is not a recommended use case for S2F, as a single protein will not benefit at all from the inferred graph (a single node), so the inferred function will be simply the combination of InterPro + HMMER.

Second, the error in the screenshot you provided could be related to insufficient memory. It may be helpful to increase the memory allocation to the process, but unfortunately I don't have a specific suggestion, as it depends heavily on the number of proteins and links that may be inferred from the ortholog calculations. 

You may try and run other commands individually, and attempt to profile/debug the step at which the process is stuck (looks like it's the collection in this case). 

To get a list of all possible commands, you may run `python S2F.py` without any subcommand, and a list would be presented to you. I plan to add more documentation to all subcommands in the future, but for now I suggest either running the script like I suggest, or have a read through the `S2F.py` script itself. 

Hope this is helpful!

P.S. I will close this issue as not planned, as I can't quite determine the reason for the Killed process.

**Comment by goes0n** [comment]
Thanks for your reply! I still have another problem when I predict three proteins. The problem is as follows (I print the related variables "k_norm" and "jac"):
![image](https://github.com/paccanarolab/S2F/assets/39076695/51a13a4f-d5e8-4abd-9344-1077fffeeb80)
![image](https://github.com/paccanarolab/S2F/assets/39076695/d7d03924-2759-4c38-abaf-5074830430b7)

What is the reason and How can I solve it?
Thanks again for your patience :)

**Comment by torresmateo** [comment]
Happy to help you with this!

For some reason this post shows only now for me in the email, and not on
GitHub.

I'm not sure what conditions triggered this dimensionality mismatch, but
please open a new issue where we could discuss this, as it does seem more
like a bug!
